pipeline {
    agent any
    tools {
        maven 'mvn v3.5.4'
    }
		triggers {
				pollSCM('* * * * *')
		}
    options { timeout(time: 10) }
    stages {
        stage("Checkout Stage") {
            steps {
                git url: 'https://github.com/superbabyformula/test-continous-delivery.git'
                echo "Checked out source code."
            }
        }
        stage("Compile Stage") {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
                sh "mvn clean compile -f calculator/"
                echo "Complied source code."
            }
        }
        stage("Unit test Stage") {
            steps {
                sh "mvn test -f calculator/"    
            }
        }
				stage("Package Stage") {
            steps {
                sh "mvn install -f calculator/"    
            }
        }
				stage("Docker Build Stage") {
					steps {
						sh "docker build -f calculator/Dockerfile -t andyworzella/calculator ."
					}
				}
				stage("Docker ps") {
					steps {
						sh "docker ps"
					}
				}
    }
}
